USE node-clean-architecture;

CREATE TABLE samples (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  data VARCHAR(255) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (id)
);
